### ISSUE TITLE
Cannot be Enabled

### ISSUE THREAD

**Issue by Armandeus66** [MrVauxs/Sequencer-JKAE-Database#3]
I have Sequencer enabled, but the checkbox for this module is grayed out, saying it cannot be enabled due to issues with dependencies. What should I do?

I use Foundry v10 with PF2E.
Sequencer, Automated Animations, Automated Animations-Warp Gate are enabled.

**Comment by MrVauxs** [comment]
Unfortunately it's a problem with the [jack kerouac's animated cartoon assets](https://github.com/jackkerouac/animated-spell-effects-cartoon) themselves. Report the issue there.
