### ISSUE TITLE
v11

### ISSUE THREAD

**Issue by brunocalado** [MrVauxs/Sequencer-JKAE-Database#4]
Please, update to v11! Tks

**Comment by MrVauxs** [comment]
[Please read the README on the front page!](https://github.com/MrVauxs/Sequencer-JKAE-Database#deprecated-you-no-longer-need-this-module-just-update-jack-kerouacs-cartoon-spell-effects-this-is-regardless-of-your-foundry-version-it-works-on-every-single-one)
